version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-18-210-214-86.compute-1.amazonaws.com
            port: '5432'
            database: dej34u0q1v3fbt
            ssl: true
            user: dinxecrwbsghvz
            password: c8ec4c7aab8288192721233fd73b40a94b91d951141f60f72ff475690dea13ba
            migrations: true